//PHIM
export const LAY_DANH_SACH_PHIM_ACTION = 'LAY_DANH_SACH_PHIM_ACTION';
export const THEM_PHIM_MOI_ACTION = 'THEM_PHIM_MOI_ACTION';
export const XOA_PHIM_ACTION = 'XOA_PHIM_ACTION';
export const MA_PHIM_CHINH_SUA_ACTION = 'MA_PHIM_CHINH_SUA_ACTION';
export const LAY_HE_THONG_RAP_ACTION = 'LAY_HE_THONG_RAP_ACTION';
export const LAY_HE_THONG_CUM_RAP_ACTION = 'LAY_HE_THONG_CUM_RAP_ACTION';

//NGƯỜI DÙNG
export const LAY_DANH_SACH_NGUOI_DUNG_ACTION = 'LAY_DANH_SACH_NGUOI_DUNG_ACTION';
export const THEM_NGUOI_DUNG_MOI_ACTION = 'THEM_NGUOI_DUNG_MOI_ACTION';
export const XOA_NGUOI_DUNG_ACTION = 'XOA_NGUOI_DUNG_ACTION';
export const TAI_KHOAN_NGUOI_DUNG_ACTION = 'TAI_KHOAN_NGUOI_DUNG_ACTION';
export const CHINH_SUA_NGUOI_DUNG_ACTION = 'CHINH_SUA_NGUOI_DUNG_ACTION';

//ĐĂNG NHẬP
export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION';
