//PHIM
export const LAY_DANH_SACH_PHIM_ACTION = 'LAY_DANH_SACH_PHIM_ACTION';
export const THEM_PHIM_MOI_ACTION = 'THEM_PHIM_MOI_ACTION';
export const XOA_PHIM_ACTION = 'XOA_PHIM_ACTION';


//NGƯỜI DÙNG
export const LAY_DANH_SACH_NGUOI_DUNG_ACTION = 'LAY_DANH_SACH_NGUOI_DUNG_ACTION';

