export const POST_SIGN_UP = 'POST_SIGN_UP';
export const POST_SIGN_IN = 'POST_SIGN_IN';
export const PUT_EDIT_INFORMATION_USER = 'PUT_EDIT_INFORMATION_USER';
export const POST_INFORMATION_ACCOUNT = 'POST_INFORMATION_ACCOUNT';