export const GET_ALL_FILM_ACTION = 'GET_ALL_FILM_ACTION'; //ok
export const GET_ALL_SYSTEM_CINEMA_ACTION = 'GET_ALL_SYSTEM_CINEMA_ACTION'; //ok
export const GET_SHOW_TIMES_BY_ID_SYSTEM_CINEMA_ACTION = 'GET_SHOW_TIMES_BY_ID_SYSTEM_CINEMA_ACTION';
export const GET_SHOW_TIMES_BY_ID_CINEMA_ACTION = 'GET_SHOW_TIMES_BY_ID_CINEMA_ACTION';
export const ACTIVE_CINEMA_ACTION = 'ACTIVE_CINEMA_ACTION';
export const CLOSE_ACTIVE_CINEMA_ACTION = 'CLOSE_ACTIVE_CINEMA_ACTION';
export const GET_DETAIL_MOVIE_BY_ID_FILM = 'GET_DETAIL_MOVIE_BY_ID_FILM';
export const GET_DETAIL_TICKET_ROOM_BY_ID_SHOW_TIMES = 'GET_DETAIL_TICKET_ROOM_BY_ID_SHOW_TIMES'; 